version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"
    steps:
      - run: 
          name: "Build Application"
          command: dotnet.exe build --configuration Release
      - run:
          name: "Deploy Application"
          command: dotnet publish -c Release --no-restore -o --destination FirstProjectHelloWorld.csproj
      - store_artifacts:
          path: jekyll/_site/docs/
          destination: circleci-docs

